#!/usr/bin/env python3
"""Generate HomeKit pairing configuration header.

Creates src/pairing_config.h with a unique setup code, QR ID, and
auto-incrementing PAIRING_CONFIG_ID. Run this once per device or
whenever you want to rotate pairing credentials.
"""

import random
import re
import os

HEADER_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "pairing_config.h")

INVALID_CODES = {str(d) * 8 for d in range(10)}  # 00000000 .. 99999999


def generate_setup_code():
    while True:
        code = "".join(str(random.randint(0, 9)) for _ in range(8))
        if code not in INVALID_CODES:
            return code


def generate_setup_id():
    chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(random.choice(chars) for _ in range(4))


def read_current_config_id(path):
    if not os.path.exists(path):
        return 0
    with open(path) as f:
        text = f.read()
    m = re.search(r"#define\s+PAIRING_CONFIG_ID\s+(\d+)", text)
    return int(m.group(1)) if m else 0


def main():
    config_id = read_current_config_id(HEADER_PATH) + 1
    setup_code = generate_setup_code()
    setup_id = generate_setup_id()

    formatted = f"{setup_code[:3]}-{setup_code[3:5]}-{setup_code[5:]}"

    content = f"""\
#pragma once
// Auto-generated by scripts/generate_pairing.py — do not edit manually

#define PAIRING_SETUP_CODE "{setup_code}"      // Displayed as {formatted}
#define PAIRING_SETUP_ID   "{setup_id}"          // 4-char QR setup ID
#define PAIRING_CONFIG_ID  {config_id}               // Incremented each generation
"""

    with open(HEADER_PATH, "w") as f:
        f.write(content)

    print(f"Generated pairing configuration:")
    print(f"  Setup code: {formatted}")
    print(f"  Setup ID:   {setup_id}")
    print(f"  Config ID:  {config_id}")
    print(f"  Written to: {os.path.abspath(HEADER_PATH)}")


if __name__ == "__main__":
    main()
