#pragma once
// Auto-generated by scripts/generate_pairing.py — do not edit manually

#define PAIRING_SETUP_CODE "38780284"      // Displayed as 387-80-284
#define PAIRING_SETUP_ID   "XX7L"          // 4-char QR setup ID
#define PAIRING_CONFIG_ID  9               // Incremented each generation
