#pragma once
// Auto-generated by scripts/generate_pairing.py — do not edit manually

#define PAIRING_SETUP_CODE "55148844"      // Displayed as 551-48-844
#define PAIRING_SETUP_ID   "3QMX"          // 4-char QR setup ID
#define PAIRING_CONFIG_ID  15               // Incremented each generation

#define FIRMWARE_MAJOR  1                   // Rolled manually
#define FIRMWARE_PATCH  0                   // Reset to 0 when PAIRING_CONFIG_ID changes
