#pragma once
// Auto-generated by scripts/generate_pairing.py — do not edit manually

#define PAIRING_SETUP_CODE "36585776"      // Displayed as 365-85-776
#define PAIRING_SETUP_ID   "QTRR"          // 4-char QR setup ID
#define PAIRING_CONFIG_ID  10               // Incremented each generation
